// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjVegetable.Models;

public partial class TImg
{
    public int FId { get; set; }

    public int FProductId { get; set; }

    public string FName { get; set; }

    public int FOrderBy { get; set; }

    public DateTime FUploadAt { get; set; }

    public int FEditor { get; set; }
}