// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjVegetable.Models;

public partial class TInventoryMain
{
    public int FId { get; set; }

    public DateOnly FBaselineDate { get; set; }

    public DateOnly FCreatedAt { get; set; }

    public int FEditor { get; set; }

    public string FNote { get; set; }
}