// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjVegetable.Models;

public partial class TInventoryDetail
{
    public int FId { get; set; }

    public int FInventoryDetailId { get; set; }

    public int FProductId { get; set; }

    public int FSystemQuantity { get; set; }

    public int FActualQuantity { get; set; }
}