// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjVegetable.Models;

public partial class TOrder
{
    public int FId { get; set; }

    public int FPersonId { get; set; }

    public int FStatus { get; set; }

    public int FPay { get; set; }

    public DateTime FOrderAt { get; set; }

    public int FTotal { get; set; }

    public string FAddress { get; set; }

    public string FReceiverName { get; set; }

    public string FPhone { get; set; }

    public string FNote { get; set; }
}