// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjVegetable.Models;

public partial class TPaymentReversalDetail
{
    public int FId { get; set; }

    public int FPaymentReversalId { get; set; }

    public int FGoodsInAndOutId { get; set; }
}