// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjVegetable.Models;

public partial class TPerson
{
    public int FId { get; set; }

    public string FName { get; set; }

    public string FAccount { get; set; }

    public string FPassword { get; set; }

    public string FGender { get; set; }

    public DateOnly FBirth { get; set; }

    public string FPhone { get; set; }

    public string FTel { get; set; }

    public string FAddress { get; set; }

    public string FEmail { get; set; }

    public string FUbn { get; set; }

    public int FPermission { get; set; }

    public string FEmp { get; set; }

    public string FEmpTel { get; set; }

    public DateTime FCreatedAt { get; set; }

    public int FEditor { get; set; }
}