// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjVegetable.Models;

public partial class TProduct
{
    public int FId { get; set; }

    public string FName { get; set; }

    public string FClassification { get; set; }

    public int FPrice { get; set; }

    public string FDescription { get; set; }

    public int FQuantity { get; set; }

    public DateTime FLaunchAt { get; set; }

    public int FStorage { get; set; }

    public string FOrigin { get; set; }

    public int FLaunch { get; set; }

    public int FEditor { get; set; }
}