// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjVegetable.Models;

public partial class TProvider
{
    public int FId { get; set; }

    public string FName { get; set; }

    public string FUbn { get; set; }

    public string FTel { get; set; }

    public string FConnect { get; set; }

    public string FAccountant { get; set; }

    public string FAddress { get; set; }

    public string FDelivery { get; set; }

    public string FInvoiceAdd { get; set; }

    public int FEditor { get; set; }
}